[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["E4", "E7", "E9", "I", "F"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["E402"]

[tool.ruff.format]
quote-style = "single"

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "ninjaproject.settings"
python_files = ["test_*.py", "*_test.py", "tests.py"]
