# Generated by Django 5.1.1 on 2024-09-04 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    'category',
                    models.CharField(
                        choices=[
                            ('Groceries', 'Groceries'),
                            ('Leisure', 'Leisure'),
                            ('Electronics', 'Electronics'),
                            ('Utilities', 'Utilities'),
                            ('Clothing', 'Clothing'),
                            ('Health', 'Health'),
                            ('Others', 'Others'),
                        ],
                        max_length=100,
                    ),
                ),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense_tracker.user')),
            ],
        ),
    ]
